/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef DMR_FEC_GOLAY20_8_H
#define DMR_FEC_GOLAY20_8_H

#ifndef __cplusplus
#error This header is C++ only!
#endif

#include <cstdint>

namespace DMR
{
namespace FEC
{

/**
 * Golay (20,8,7) code, ETSI TS 102 361-1 V2.5.1 clause B.3.1.
 *
 * The code is obtained by shortening the Golay code generated by
 * g(x) = x^11 + x^10 + x^6 + x^5 + x^4 + x^2 + 1 and protects the Slot Type
 * PDU (clause 9.1.3). A codeword is laid out as:
 *
 * +--------+---------+
 * |  data  | parity  |
 * +--------+---------+
 * | 8 bit  | 12 bit  |
 * +--------+---------+
 *
 * with the first row of the generator matrix (table B.11) being the MSB of
 * the data field. The minimum distance of 7 allows the correction of up to
 * three bit errors.
 */
namespace Golay20_8
{

/**
 * Compute the 12 parity bits of an 8-bit data block using the generator
 * matrix of table B.11.
 *
 * @param data: input data.
 * @return 12-bit parity.
 */
uint16_t parity(uint8_t data);

/**
 * Encode an 8-bit data block into a 20-bit codeword.
 *
 * @param data: input data.
 * @return 20-bit codeword, data in bits 19..12 and parity in bits 11..0.
 */
uint32_t encode(uint8_t data);

/**
 * Decode a 20-bit codeword, correcting up to three bit errors.
 *
 * @param codeword: input codeword, bits 31..20 are ignored.
 * @param data: destination for the decoded data block.
 * @return number of corrected bit errors or -1 if the codeword cannot be
 * corrected, in which case data is left untouched.
 */
int decode(uint32_t codeword, uint8_t &data);

} // namespace Golay20_8
} // namespace FEC
} // namespace DMR

#endif // DMR_FEC_GOLAY20_8_H
