/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef DMR_FEC_QR16_7_6_H
#define DMR_FEC_QR16_7_6_H

#ifndef __cplusplus
#error This header is C++ only!
#endif

#include <cstdint>

namespace DMR
{
namespace FEC
{

/**
 * Quadratic residue (16,7,6) code, ETSI TS 102 361-1 V2.5.1 clause B.3.2.
 *
 * The code is obtained from the (17,9,5) quadratic residue code generated by
 * G(x) = x^8 + x^5 + x^4 + x^3 + 1 by deleting two information bits and
 * appending an overall parity bit. It protects the EMB PDU (clause 9.1.2).
 * A codeword is laid out as:
 *
 * +--------+---------+
 * |  data  | parity  |
 * +--------+---------+
 * | 7 bit  |  9 bit  |
 * +--------+---------+
 *
 * with the first row of the generator matrix (table B.12) being the MSB of
 * the data field. The minimum distance of 6 allows the correction of up to
 * two bit errors and the detection of three.
 */
namespace QR16_7_6
{

/**
 * Compute the 9 parity bits of a 7-bit data block using the generator
 * matrix of table B.12.
 *
 * @param data: input data, bit 7 is ignored.
 * @return 9-bit parity.
 */
uint16_t parity(uint8_t data);

/**
 * Encode a 7-bit data block into a 16-bit codeword.
 *
 * @param data: input data, bit 7 is ignored.
 * @return 16-bit codeword, data in bits 15..9 and parity in bits 8..0.
 */
uint16_t encode(uint8_t data);

/**
 * Decode a 16-bit codeword, correcting up to two bit errors.
 *
 * @param codeword: input codeword.
 * @param data: destination for the decoded data block.
 * @return number of corrected bit errors or -1 if the codeword cannot be
 * corrected, in which case data is left untouched.
 */
int decode(uint16_t codeword, uint8_t &data);

} // namespace QR16_7_6
} // namespace FEC
} // namespace DMR

#endif // DMR_FEC_QR16_7_6_H
