/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef DMR_FEC_RS12_9_H
#define DMR_FEC_RS12_9_H

#ifndef __cplusplus
#error This header is C++ only!
#endif

#include <cstdint>

namespace DMR
{
namespace FEC
{

/**
 * Reed-Solomon (12,9,4) code over GF(2^8), ETSI TS 102 361-1 V2.5.1 clause
 * B.3.6. The field is generated by the primitive polynomial
 * a^8 + a^4 + a^3 + a^2 + 1 (equation B.14) and the code by
 * g(x) = (x + a)(x + a^2)(x + a^3) = x^3 + 0x0E x^2 + 0x38 x + 0x40
 * (equations B.9 and B.10). It protects the 72-bit Full LC carried by the
 * voice LC header and the terminator with LC (clauses 7.1.1 and 7.1.2),
 * where the three parity octets are XORed with the Data Type CRC mask of
 * clause B.3.12 (0x969696 for the header, 0x999999 for the terminator).
 *
 * A codeword c = (m8, m7, ..., m0, p2, p1, p0) is stored as 12 octets with
 * m8 first (equation B.13). The minimum distance of 4 allows the correction
 * of one symbol error.
 */
namespace Rs12_9
{

/**
 * Multiply two elements of GF(2^8).
 *
 * @param a: first operand.
 * @param b: second operand.
 * @return product in the field.
 */
uint8_t gfMul(uint8_t a, uint8_t b);

/**
 * Compute the three parity octets of a 9-octet message.
 *
 * @param message: input message m8..m0.
 * @param parity: destination for the parity octets p2, p1, p0.
 */
void encode(const uint8_t message[9], uint8_t parity[3]);

/**
 * Compute the Full LC codeword with the parity masked by the Data Type CRC
 * mask, ready for the BPTC (196,96) encoder.
 *
 * @param lc: 72-bit Full LC.
 * @param mask: 24-bit Data Type CRC mask, Crc::MASK_VOICE_LC_HEADER or
 * Crc::MASK_TERMINATOR_WITH_LC.
 * @param codeword: destination for the 96-bit codeword.
 */
void encodeLc(const uint8_t lc[9], uint32_t mask, uint8_t codeword[12]);

/**
 * Check a codeword and correct up to one symbol error in place.
 *
 * @param codeword: 12-octet codeword with unmasked parity.
 * @return number of corrected symbol errors (0 or 1) or -1 if the codeword
 * cannot be corrected, in which case it is left untouched.
 */
int decode(uint8_t codeword[12]);

/**
 * Unmask and decode a Full LC codeword produced by the BPTC (196,96)
 * decoder.
 *
 * @param codeword: 96-bit codeword with masked parity.
 * @param mask: 24-bit Data Type CRC mask used by the transmitter.
 * @param lc: destination for the 72-bit Full LC.
 * @return number of corrected symbol errors (0 or 1) or -1 if the codeword
 * cannot be corrected, in which case lc is left untouched.
 */
int decodeLc(const uint8_t codeword[12], uint32_t mask, uint8_t lc[9]);

} // namespace Rs12_9
} // namespace FEC
} // namespace DMR

#endif // DMR_FEC_RS12_9_H
