/*
 * SPDX-FileCopyrightText: Copyright 2020-2026 OpenRTX Contributors
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

/*
 * Unit tests for the DMR FEC reference module, ETSI TS 102 361-1 V2.5.1
 * Annex B.
 *
 * The golden vectors in assets/DMR_fec_vectors.inc are generated by
 * assets/gen_DMR_fec_vectors.py with dmr_utils3 0.1.31 as the oracle,
 * cross-checked there against the generator matrices of Annex B. The
 * captured_voice_header_burst vector is an over-the-air voice LC header
 * (33 bytes, 264 bits) taken from the dmr_utils3 bptc.py self-test data
 * and is used as an independent end-to-end check of the BPTC (196,96),
 * Reed-Solomon (12,9) with header mask, Golay (20,8) Slot Type and SYNC
 * layout of a general data burst.
 */

#include <catch2/catch_test_macros.hpp>
#include <cstdint>
#include <cstring>
#include <random>
#include "protocols/DMR/FEC/Golay20_8.hpp"
#include "protocols/DMR/FEC/QR16_7_6.hpp"
#include "protocols/DMR/FEC/Hamming.hpp"
#include "protocols/DMR/FEC/Bptc196_96.hpp"
#include "protocols/DMR/FEC/Rs12_9.hpp"
#include "protocols/DMR/FEC/Crc.hpp"
#include "protocols/DMR/FEC/EmbeddedLc.hpp"
#include "protocols/DMR/FEC/SlotType.hpp"
#include "protocols/DMR/FEC/Emb.hpp"

#include "assets/DMR_fec_vectors.inc"

using namespace DMR::FEC;

static std::default_random_engine rng;

/**
 * Compare two byte arrays, reporting the first mismatch.
 */
static bool sameBytes(const uint8_t *a, const uint8_t *b, size_t len)
{
    for (size_t i = 0; i < len; i++) {
        if (a[i] != b[i]) {
            UNSCOPED_INFO("mismatch at byte " << i << ": " << int(a[i])
                                              << " != " << int(b[i]));
            return false;
        }
    }

    return true;
}

/**
 * Flip a bit of a packed MSB-first bit string.
 */
static void flipBit(uint8_t *bytes, unsigned pos)
{
    bytes[pos / 8] ^= 1 << (7 - (pos % 8));
}

/*
 * Golay (20,8), clause B.3.1
 */

TEST_CASE("Golay(20,8) parity matches the generator matrix table",
          "[dmr][fec][golay]")
{
    for (unsigned d = 0; d < 256; d++) {
        REQUIRE(Golay20_8::parity(d) == golay20_8_parity[d]);
        REQUIRE(Golay20_8::encode(d) == ((d << 12) | golay20_8_parity[d]));
    }
}

TEST_CASE("Golay(20,8) corrects every pattern of up to three errors",
          "[dmr][fec][golay]")
{
    for (unsigned d = 0; d < 256; d++) {
        uint32_t cw = Golay20_8::encode(d);
        uint8_t out = 0xFF;

        REQUIRE(Golay20_8::decode(cw, out) == 0);
        REQUIRE(out == d);

        for (unsigned i = 0; i < 20; i++) {
            REQUIRE(Golay20_8::decode(cw ^ (1u << i), out) == 1);
            REQUIRE(out == d);

            for (unsigned j = i + 1; j < 20; j++) {
                uint32_t e2 = (1u << i) | (1u << j);
                REQUIRE(Golay20_8::decode(cw ^ e2, out) == 2);
                REQUIRE(out == d);

                for (unsigned k = j + 1; k < 20; k++) {
                    uint32_t e3 = e2 | (1u << k);
                    REQUIRE(Golay20_8::decode(cw ^ e3, out) == 3);
                    REQUIRE(out == d);
                }
            }
        }
    }
}

TEST_CASE("Golay(20,8) codewords have minimum distance 7", "[dmr][fec][golay]")
{
    // Linear code: the minimum distance is the minimum nonzero weight
    for (unsigned d = 1; d < 256; d++)
        REQUIRE(__builtin_popcount(Golay20_8::encode(d)) >= 7);
}

/*
 * Quadratic residue (16,7,6), clause B.3.2
 */

TEST_CASE("QR(16,7,6) parity matches the generator matrix table",
          "[dmr][fec][qr]")
{
    for (unsigned d = 0; d < 128; d++) {
        REQUIRE(QR16_7_6::parity(d) == qr16_7_6_parity[d]);
        REQUIRE(QR16_7_6::encode(d) == ((d << 9) | qr16_7_6_parity[d]));
    }
}

TEST_CASE("QR(16,7,6) corrects two errors and rejects three", "[dmr][fec][qr]")
{
    for (unsigned d = 0; d < 128; d++) {
        uint16_t cw = QR16_7_6::encode(d);
        uint8_t out = 0xFF;

        REQUIRE(QR16_7_6::decode(cw, out) == 0);
        REQUIRE(out == d);

        for (unsigned i = 0; i < 16; i++) {
            REQUIRE(QR16_7_6::decode(cw ^ (1u << i), out) == 1);
            REQUIRE(out == d);

            for (unsigned j = i + 1; j < 16; j++) {
                uint16_t e2 = (1u << i) | (1u << j);
                REQUIRE(QR16_7_6::decode(cw ^ e2, out) == 2);
                REQUIRE(out == d);

                for (unsigned k = j + 1; k < 16; k++) {
                    uint16_t e3 = e2 | (1u << k);
                    uint8_t junk = 0;
                    REQUIRE(QR16_7_6::decode(cw ^ e3, junk) == -1);
                }
            }
        }
    }
}

TEST_CASE("QR(16,7,6) codewords have minimum distance 6", "[dmr][fec][qr]")
{
    for (unsigned d = 1; d < 128; d++)
        REQUIRE(__builtin_popcount(QR16_7_6::encode(d)) >= 6);
}

/*
 * Hamming codes, clauses B.3.3 to B.3.5
 */

struct HammingCase {
    const char *name;
    const Hamming::Code &code;
    const uint16_t *vectors;
    unsigned minDistance;
};

static const HammingCase hammingCases[] = {
    { "(7,4,3)", Hamming::H7_4, hamming7_4_vectors, 3 },
    { "(13,9,3)", Hamming::H13_9, hamming13_9_vectors, 3 },
    { "(15,11,3)", Hamming::H15_11, hamming15_11_vectors, 3 },
    { "(16,11,4)", Hamming::H16_11, hamming16_11_vectors, 4 },
    { "(17,12,3)", Hamming::H17_12, hamming17_12_vectors, 3 },
};

TEST_CASE("Hamming parity matches the generator matrices",
          "[dmr][fec][hamming]")
{
    for (const auto &c : hammingCases) {
        INFO("Hamming " << c.name);
        for (unsigned i = 0; i < 16; i++) {
            uint16_t data = c.vectors[2 * i];
            uint16_t par = c.vectors[2 * i + 1];
            REQUIRE(Hamming::parity(c.code, data) == par);
            REQUIRE(Hamming::encode(c.code, data)
                    == ((uint32_t(data) << c.code.parityBits) | par));
            REQUIRE(Hamming::data(c.code, Hamming::encode(c.code, data))
                    == data);
        }
    }
}

TEST_CASE("Hamming codes have the declared minimum distance",
          "[dmr][fec][hamming]")
{
    for (const auto &c : hammingCases) {
        INFO("Hamming " << c.name);
        for (unsigned d = 1; d < (1u << c.code.dataBits); d++) {
            REQUIRE(unsigned(__builtin_popcount(Hamming::encode(c.code, d)))
                    >= c.minDistance);
        }
    }
}

TEST_CASE("Hamming codes correct any single bit error", "[dmr][fec][hamming]")
{
    for (const auto &c : hammingCases) {
        INFO("Hamming " << c.name);
        unsigned n = c.code.dataBits + c.code.parityBits;

        for (unsigned d = 0; d < (1u << c.code.dataBits); d++) {
            uint32_t cw = Hamming::encode(c.code, d);
            uint32_t w = cw;
            REQUIRE(Hamming::decode(c.code, w) == 0);
            REQUIRE(w == cw);

            for (unsigned i = 0; i < n; i++) {
                w = cw ^ (1u << i);
                REQUIRE(Hamming::decode(c.code, w) == 1);
                REQUIRE(w == cw);
            }
        }
    }
}

TEST_CASE("Hamming(16,11,4) detects any double bit error",
          "[dmr][fec][hamming]")
{
    for (unsigned d = 0; d < 2048; d++) {
        uint32_t cw = Hamming::encode(Hamming::H16_11, d);

        for (unsigned i = 0; i < 16; i++) {
            for (unsigned j = i + 1; j < 16; j++) {
                uint32_t w = cw ^ (1u << i) ^ (1u << j);
                REQUIRE(Hamming::decode(Hamming::H16_11, w) == -1);
            }
        }
    }
}

TEST_CASE("Hamming(7,4) protects the CACH TACT bits", "[dmr][fec][hamming]")
{
    // TACT: AT = 1, TC = 0, LCSS = 00 (table 9.5) -> data 1000
    uint32_t cw = Hamming::encode(Hamming::H7_4, 0x8);
    REQUIRE(cw == 0x45); // 1000 101, table B.17 first row
    REQUIRE(Hamming::data(Hamming::H7_4, cw) == 0x8);
}

/*
 * BPTC (196,96), clause B.1.1
 */

TEST_CASE("BPTC(196,96) interleaver is a permutation", "[dmr][fec][bptc]")
{
    bool seen[196] = { false };

    for (unsigned i = 0; i < 196; i++) {
        uint8_t k = Bptc196_96::interleaveIndex(i);
        REQUIRE(k < 196);
        REQUIRE(seen[k] == false);
        seen[k] = true;
    }

    // Spot checks against table B.2
    REQUIRE(Bptc196_96::interleaveIndex(0) == 0);
    REQUIRE(Bptc196_96::interleaveIndex(1) == 181);
    REQUIRE(Bptc196_96::interleaveIndex(13) == 1);
    REQUIRE(Bptc196_96::interleaveIndex(131) == 191);
    REQUIRE(Bptc196_96::interleaveIndex(195) == 15);
}

TEST_CASE("BPTC(196,96) encodes the golden vectors", "[dmr][fec][bptc]")
{
    for (const auto &v : bptc_vectors) {
        uint8_t data[12];
        uint8_t tx[25];

        memcpy(data, v.lc, 9);
        memcpy(&data[9], v.headerParity, 3);
        Bptc196_96::encode(data, tx);
        REQUIRE(sameBytes(tx, v.header, 25));

        memcpy(&data[9], v.terminatorParity, 3);
        Bptc196_96::encode(data, tx);
        REQUIRE(sameBytes(tx, v.terminator, 25));
    }
}

TEST_CASE("BPTC(196,96) decode is the inverse of encode", "[dmr][fec][bptc]")
{
    for (const auto &v : bptc_vectors) {
        uint8_t data[12];
        uint8_t expected[12];

        memcpy(expected, v.lc, 9);
        memcpy(&expected[9], v.headerParity, 3);
        REQUIRE(Bptc196_96::decode(v.header, data) == 0);
        REQUIRE(sameBytes(data, expected, 12));

        memcpy(&expected[9], v.terminatorParity, 3);
        REQUIRE(Bptc196_96::decode(v.terminator, data) == 0);
        REQUIRE(sameBytes(data, expected, 12));
    }

    std::uniform_int_distribution<int> byte(0, 255);
    for (unsigned n = 0; n < 200; n++) {
        uint8_t data[12];
        uint8_t tx[25];
        uint8_t out[12];

        for (auto &b : data)
            b = byte(rng);

        Bptc196_96::encode(data, tx);
        REQUIRE((tx[24] & 0x0F) == 0);
        REQUIRE(Bptc196_96::decode(tx, out) == 0);
        REQUIRE(sameBytes(out, data, 12));
    }
}

TEST_CASE("BPTC(196,96) corrects one error per row and per column",
          "[dmr][fec][bptc]")
{
    uint8_t data[12];
    uint8_t clean[25];
    uint8_t out[12];

    memcpy(data, bptc_vectors[1].lc, 9);
    memcpy(&data[9], bptc_vectors[1].headerParity, 3);
    Bptc196_96::encode(data, clean);

    // One error in each of the nine rows, in different columns (matrix
    // index 1 + 15 * row + col, then interleaved)
    uint8_t tx[25];
    memcpy(tx, clean, 25);
    for (unsigned row = 0; row < 9; row++) {
        unsigned col = (row * 3) % 15;
        flipBit(tx, Bptc196_96::interleaveIndex(1 + 15 * row + col));
    }

    REQUIRE(Bptc196_96::decode(tx, out) == 9);
    REQUIRE(sameBytes(out, data, 12));

    // One error in each of thirteen columns, in thirteen different rows
    // (rows 9 to 12 hold the column parity bits)
    memcpy(tx, clean, 25);
    for (unsigned col = 0; col < 13; col++) {
        unsigned row = col;
        unsigned idx = (row < 9) ? (1 + 15 * row + col) :
                                   (136 + 15 * (row - 9) + col);
        flipBit(tx, Bptc196_96::interleaveIndex(idx));
    }

    REQUIRE(Bptc196_96::decode(tx, out) == 13);
    REQUIRE(sameBytes(out, data, 12));

    // Any single error in the transmit array. TX(195), the pad bit R(3),
    // is not covered by any row or column code and is simply ignored.
    for (unsigned pos = 0; pos < 196; pos++) {
        int expected = (pos == Bptc196_96::interleaveIndex(0)) ? 0 : 1;

        memcpy(tx, clean, 25);
        flipBit(tx, pos);
        INFO("error at TX(" << (195 - pos) << ")");
        REQUIRE(Bptc196_96::decode(tx, out) == expected);
        REQUIRE(sameBytes(out, data, 12));
    }
}

/*
 * Reed-Solomon (12,9), clause B.3.6, with the masks of clause B.3.12
 */

TEST_CASE("GF(2^8) arithmetic", "[dmr][fec][rs]")
{
    // a^8 = a^4 + a^3 + a^2 + 1, equation (B.14): 0x02^8 = 0x1D
    uint8_t p = 1;
    for (unsigned i = 0; i < 8; i++)
        p = Rs12_9::gfMul(p, 0x02);
    REQUIRE(p == 0x1D);

    // Table B.19 spot checks: a^16 = 0x4C, a^100 = 0x11, a^254 = 0x8E
    uint8_t v = 1;
    for (unsigned i = 1; i <= 254; i++) {
        v = Rs12_9::gfMul(v, 0x02);
        if (i == 16)
            REQUIRE(v == 0x4C);
        if (i == 100)
            REQUIRE(v == 0x11);
    }
    REQUIRE(v == 0x8E);
    REQUIRE(Rs12_9::gfMul(v, 0x02) == 0x01); // a^255 = 1

    for (unsigned a = 0; a < 256; a++) {
        REQUIRE(Rs12_9::gfMul(a, 1) == a);
        REQUIRE(Rs12_9::gfMul(a, 0) == 0);
        REQUIRE(Rs12_9::gfMul(a, 0x57) == Rs12_9::gfMul(0x57, a));
    }
}

TEST_CASE("RS(12,9) generator matrix rows", "[dmr][fec][rs]")
{
    // Table B.18: the parity of a unit message is the corresponding row
    static const uint8_t rows[9][3] = {
        { 0x1C, 0xBC, 0xFD }, { 0x89, 0x31, 0x08 }, { 0xAD, 0x41, 0x36 },
        { 0x7D, 0x71, 0x16 }, { 0xF3, 0xA6, 0x3A }, { 0x08, 0x83, 0x7B },
        { 0x3F, 0x6F, 0x02 }, { 0x6C, 0x0D, 0xA7 }, { 0x0E, 0x38, 0x40 },
    };

    for (unsigned i = 0; i < 9; i++) {
        uint8_t msg[9] = { 0 };
        uint8_t parity[3];

        msg[i] = 0x01;
        Rs12_9::encode(msg, parity);
        REQUIRE(sameBytes(parity, rows[i], 3));
    }
}

TEST_CASE("RS(12,9) masked parity of the golden vectors", "[dmr][fec][rs]")
{
    for (const auto &v : bptc_vectors) {
        uint8_t cw[12];
        uint8_t lc[9];

        Rs12_9::encodeLc(v.lc, Crc::MASK_VOICE_LC_HEADER, cw);
        REQUIRE(sameBytes(cw, v.lc, 9));
        REQUIRE(sameBytes(&cw[9], v.headerParity, 3));
        REQUIRE(Rs12_9::decodeLc(cw, Crc::MASK_VOICE_LC_HEADER, lc) == 0);
        REQUIRE(sameBytes(lc, v.lc, 9));

        // The wrong mask must not validate
        uint8_t junk[9];
        REQUIRE(Rs12_9::decodeLc(cw, Crc::MASK_TERMINATOR_WITH_LC, junk) == -1);

        Rs12_9::encodeLc(v.lc, Crc::MASK_TERMINATOR_WITH_LC, cw);
        REQUIRE(sameBytes(&cw[9], v.terminatorParity, 3));
        REQUIRE(Rs12_9::decodeLc(cw, Crc::MASK_TERMINATOR_WITH_LC, lc) == 0);
        REQUIRE(sameBytes(lc, v.lc, 9));
    }
}

TEST_CASE("RS(12,9) corrects one symbol and detects two", "[dmr][fec][rs]")
{
    std::uniform_int_distribution<int> byte(0, 255);
    std::uniform_int_distribution<int> nonzero(1, 255);

    for (unsigned n = 0; n < 50; n++) {
        uint8_t cw[12];
        uint8_t rx[12];

        for (unsigned i = 0; i < 9; i++)
            cw[i] = byte(rng);
        Rs12_9::encode(cw, &cw[9]);

        memcpy(rx, cw, 12);
        REQUIRE(Rs12_9::decode(rx) == 0);
        REQUIRE(sameBytes(rx, cw, 12));

        for (unsigned pos = 0; pos < 12; pos++) {
            memcpy(rx, cw, 12);
            rx[pos] ^= nonzero(rng);
            REQUIRE(Rs12_9::decode(rx) == 1);
            REQUIRE(sameBytes(rx, cw, 12));

            for (unsigned pos2 = pos + 1; pos2 < 12; pos2++) {
                memcpy(rx, cw, 12);
                rx[pos] ^= nonzero(rng);
                rx[pos2] ^= nonzero(rng);
                REQUIRE(Rs12_9::decode(rx) == -1);
            }
        }
    }
}

/*
 * CRCs and checksums, clauses B.3.7, B.3.8 and B.3.11
 */

TEST_CASE("CRC-8 of clause B.3.7", "[dmr][fec][crc]")
{
    // Standard CRC-8 (poly 0x07, init 0, no reflection) check value
    static const uint8_t check[9] = { '1', '2', '3', '4', '5',
                                      '6', '7', '8', '9' };
    REQUIRE(Crc::crc8(check, 9) == 0xF4);

    // x^8 mod G8(x) = x^2 + x + 1
    REQUIRE(Crc::crc8Bits(0x000001, 24) == 0x07);
    REQUIRE(Crc::crc8Bits(0, 24) == 0x00);

    // Hash ID of a 24-bit destination address is the same through both
    // interfaces
    static const uint8_t dst[3] = { 0x2F, 0x9B, 0xE5 };
    REQUIRE(Crc::crc8Bits(0x2F9BE5, 24) == Crc::crc8(dst, 3));

    // Linearity of the remainder
    REQUIRE((Crc::crc8Bits(0x123456, 24) ^ Crc::crc8Bits(0x0F0F0F, 24))
            == Crc::crc8Bits(0x123456 ^ 0x0F0F0F, 24));
}

TEST_CASE("CRC-CCITT of clause B.3.8", "[dmr][fec][crc]")
{
    // CRC-16/XMODEM check value 0x31C3, inverted by IH(x)
    static const uint8_t check[9] = { '1', '2', '3', '4', '5',
                                      '6', '7', '8', '9' };
    REQUIRE(Crc::crcCcitt(check, 9) == (0x31C3 ^ 0xFFFF));
    REQUIRE(Crc::crcCcitt(check, 0) == 0xFFFF);

    // Data Type CRC mask, clause B.3.12
    REQUIRE(Crc::crcCcitt(check, 9, Crc::MASK_CSBK)
            == (0x31C3 ^ 0xFFFF ^ 0xA5A5));
    REQUIRE(Crc::MASK_PI_HEADER == 0x6969);
    REQUIRE(Crc::MASK_VOICE_LC_HEADER == 0x969696);
    REQUIRE(Crc::MASK_TERMINATOR_WITH_LC == 0x999999);
    REQUIRE(Crc::MASK_DATA_HEADER == 0xCCCC);

    // Appending the transmitted CRC yields a constant remainder
    uint8_t msg[12];
    std::uniform_int_distribution<int> byte(0, 255);
    for (unsigned n = 0; n < 100; n++) {
        for (unsigned i = 0; i < 10; i++)
            msg[i] = byte(rng);

        uint16_t crc = Crc::crcCcitt(msg, 10);
        msg[10] = crc >> 8;
        msg[11] = crc & 0xFF;
        REQUIRE(Crc::crcCcitt(msg, 12) == 0xE2F0);
    }
}

TEST_CASE("5-bit checksum of clause B.3.11", "[dmr][fec][crc]")
{
    for (const auto &v : bptc_vectors)
        REQUIRE(Crc::checksum5(v.lc) == v.checksum5);

    static const uint8_t zero[9] = { 0 };
    static const uint8_t max[9] = {
        255, 255, 255, 255, 255, 255, 255, 255, 255
    };
    static const uint8_t one[9] = { 31, 0, 0, 0, 0, 0, 0, 0, 30 };
    REQUIRE(Crc::checksum5(zero) == 0);
    REQUIRE(Crc::checksum5(max) == (2295 % 31));
    REQUIRE(Crc::checksum5(one) == 30);
}

/*
 * Embedded LC, clauses B.2.1 and 7.1.3
 */

TEST_CASE("Embedded LC fragments match the golden vectors", "[dmr][fec][emblc]")
{
    for (const auto &v : bptc_vectors) {
        uint32_t frags[4];
        uint8_t lc[9];

        EmbeddedLc::encode(v.lc, frags);
        for (unsigned i = 0; i < 4; i++) {
            INFO("fragment " << i);
            REQUIRE(frags[i] == v.embedded[i]);
        }

        REQUIRE(EmbeddedLc::decode(frags, lc) == 0);
        REQUIRE(sameBytes(lc, v.lc, 9));
    }
}

TEST_CASE("Embedded LC interleaving follows figure B.3", "[dmr][fec][emblc]")
{
    // Only LC(71), LC(60) and LC(0) set: first fragment starts with
    // LC(71) LC(60) LC(49) ... LC(9) PC(15), fourth ends with PC(0)
    uint8_t lc[9] = { 0x80, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01 };
    uint32_t frags[4];

    EmbeddedLc::encode(lc, frags);
    REQUIRE((frags[0] >> 31) == 1);       // LC(71)
    REQUIRE(((frags[0] >> 30) & 1) == 1); // LC(60)
    REQUIRE(((frags[0] >> 29) & 1) == 0); // LC(49)

    // LC(0) is row 6 column 9: fragment 2 (columns 8..11), column 9 -> bit
    // offset 8 + row 6 = 14 from the fragment MSB
    REQUIRE(((frags[2] >> (31 - 14)) & 1) == 1);

    // Column parity: LC(71), LC(60) both in column 0 -> PC(15) = 0 plus
    // the Hamming parity of rows 0 and 1
    uint16_t rows[8] = { 0 };
    for (unsigned col = 0; col < 16; col++) {
        for (unsigned row = 0; row < 8; row++) {
            unsigned pos = col * 8 + row;
            unsigned bit = (frags[pos / 32] >> (31 - (pos % 32))) & 1;
            rows[row] |= bit << (15 - col);
        }
    }

    uint16_t parity = 0;
    for (unsigned row = 0; row < 8; row++)
        parity ^= rows[row];
    REQUIRE(parity == 0);

    for (unsigned row = 0; row < 7; row++) {
        uint32_t w = rows[row];
        REQUIRE(Hamming::decode(Hamming::H16_11, w) == 0);
    }

    REQUIRE(Hamming::data(Hamming::H16_11, rows[0]) == 0x400); // LC(71)
    REQUIRE(Hamming::data(Hamming::H16_11, rows[1]) == 0x400); // LC(60)
    REQUIRE(Hamming::data(Hamming::H16_11, rows[6])
            == ((0x002 | (Crc::checksum5(lc) & 1))));          // LC(0), CS(0)
}

TEST_CASE("Embedded LC corrects a single error in any position",
          "[dmr][fec][emblc]")
{
    for (const auto &v : bptc_vectors) {
        for (unsigned pos = 0; pos < 128; pos++) {
            uint32_t frags[4];
            uint8_t lc[9];

            memcpy(frags, v.embedded, sizeof(frags));
            frags[pos / 32] ^= 1u << (31 - (pos % 32));
            INFO("error at bit " << pos);
            REQUIRE(EmbeddedLc::decode(frags, lc) == 1);
            REQUIRE(sameBytes(lc, v.lc, 9));
        }
    }
}

TEST_CASE("Embedded LC rejects corrupted messages", "[dmr][fec][emblc]")
{
    uint32_t frags[4];
    uint8_t lc[9];

    // Two errors in the same row are detected by the (16,11,4) code
    memcpy(frags, bptc_vectors[0].embedded, sizeof(frags));
    frags[0] ^= 0x80000000; // row 0, column 0
    frags[0] ^= 0x00800000; // row 0, column 1
    REQUIRE(EmbeddedLc::decode(frags, lc) == -1);

    // A wrong checksum is detected
    uint8_t bad[9];
    memcpy(bad, bptc_vectors[0].lc, 9);
    EmbeddedLc::encode(bad, frags);
    frags[0] ^= 0x20000000; // row 2 column 0: LC(49)
    frags[0] ^= 0x00200000; // row 2 column 1: LC(48), same row
    REQUIRE(EmbeddedLc::decode(frags, lc) == -1);
}

/*
 * Slot Type and EMB PDUs, clauses 9.1.3 and 9.1.2
 */

TEST_CASE("Slot Type PDU round trip", "[dmr][fec][slottype]")
{
    for (unsigned cc = 0; cc < 16; cc++) {
        for (unsigned dt = 0; dt < 16; dt++) {
            uint32_t pdu = SlotType::encode(cc, dt);
            uint8_t rxCc = 0xFF, rxDt = 0xFF;

            REQUIRE((pdu >> 16) == cc);
            REQUIRE(((pdu >> 12) & 0xF) == dt);
            REQUIRE((pdu & 0xFFF) == golay20_8_parity[(cc << 4) | dt]);
            REQUIRE(SlotType::decode(pdu ^ 0x00021, rxCc, rxDt) == 2);
            REQUIRE(rxCc == cc);
            REQUIRE(rxDt == dt);
        }
    }
}

TEST_CASE("EMB PDU round trip and known values", "[dmr][fec][emb]")
{
    // CC 1, PI 0, LCSS 00..11: 0x11E2, 0x1391, 0x1507, 0x1774
    REQUIRE(Emb::encode(1, false, 0) == 0x11E2);
    REQUIRE(Emb::encode(1, false, 1) == 0x1391);
    REQUIRE(Emb::encode(1, false, 2) == 0x1507);
    REQUIRE(Emb::encode(1, false, 3) == 0x1774);

    for (unsigned cc = 0; cc < 16; cc++) {
        for (unsigned pi = 0; pi < 2; pi++) {
            for (unsigned lcss = 0; lcss < 4; lcss++) {
                uint16_t pdu = Emb::encode(cc, pi != 0, lcss);
                uint8_t rxCc = 0xFF, rxLcss = 0xFF;
                bool rxPi = !pi;

                REQUIRE((pdu >> 12) == cc);
                REQUIRE(((pdu >> 11) & 1) == pi);
                REQUIRE(((pdu >> 9) & 3) == lcss);
                REQUIRE(Emb::decode(pdu ^ 0x8001, rxCc, rxPi, rxLcss) == 2);
                REQUIRE(rxCc == cc);
                REQUIRE(rxPi == (pi != 0));
                REQUIRE(rxLcss == lcss);
            }
        }
    }
}

/*
 * End-to-end check on an over-the-air voice LC header burst
 */

TEST_CASE("Captured voice LC header burst decodes end to end",
          "[dmr][fec][burst]")
{
    const uint8_t *burst = captured_voice_header_burst;
    uint8_t tx[25];
    uint8_t data[12];
    uint8_t lc[9];
    uint8_t cc = 0, dt = 0;

    // SYNC field, bits 108..155: BS sourced data (table 9.2)
    static const uint8_t bsDataSync[6] = { 0xDF, 0xF5, 0x7D, 0x75, 0xDF, 0x5D };
    uint8_t sync[6];
    for (unsigned i = 0; i < 48; i++) {
        unsigned pos = 108 + i;
        unsigned bit = (burst[pos / 8] >> (7 - (pos % 8))) & 1;
        if (i % 8 == 0)
            sync[i / 8] = 0;
        sync[i / 8] |= bit << (7 - (i % 8));
    }
    REQUIRE(sameBytes(sync, bsDataSync, 6));

    // Slot Type: colour code 1, Voice LC Header (table 9.22)
    REQUIRE(SlotType::decode(SlotType::fromBurst(burst), cc, dt) == 0);
    REQUIRE(cc == 1);
    REQUIRE(dt == 1);

    // Payload: BPTC then RS with the header mask
    Bptc196_96::fromBurst(burst, tx);
    REQUIRE(sameBytes(tx, bptc_vectors[0].header, 25));
    REQUIRE(Bptc196_96::decode(tx, data) == 0);
    REQUIRE(Rs12_9::decodeLc(data, Crc::MASK_VOICE_LC_HEADER, lc) == 0);
    REQUIRE(sameBytes(lc, bptc_vectors[0].lc, 9));

    // Group voice call (FLCO 0), FID 0x10, dst 3120, src 3120101
    REQUIRE(lc[0] == 0x00);
    REQUIRE(lc[1] == 0x10);
    uint32_t dst = (uint32_t(lc[3]) << 16) | (uint32_t(lc[4]) << 8) | lc[5];
    uint32_t src = (uint32_t(lc[6]) << 16) | (uint32_t(lc[7]) << 8) | lc[8];
    REQUIRE(dst == 3120);
    REQUIRE(src == 3120101);
}
